document.writeln("<head>");
document.writeln("<title>飓跃网络加速器</title>");
document.writeln("<meta charset=\'utf-8\'/>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1, user-scalable=no\'/>");
document.writeln("<meta name=\'format-detection\' content=\'telephone=no\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\'>");
document.writeln("<link rel=\'icon\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs/ss5r/favicon.ico\' type=\'image/x-icon\'>");
document.writeln("<link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs/ss5r/lsedog/css/style-index.css\'>");
document.writeln("</head>");
document.writeln("<body><section class=\'national-parks-top\'><a id=\'Mzone1\' class=\'block\' href=\'https://jyssr.net/index.php\'>");
document.writeln("<div class=\'cb-slideshow\'>");
document.writeln("	<img class=\'nat-park-logo\' alt=\'text-png-size\' src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs/ss5r/images/logo.png\'>");
document.writeln("	<ul>");
document.writeln("		<li><span>Image 01</span></li>");
document.writeln("		<li><span>Image 02</span></li>");
document.writeln("		<li><span>Image 03</span></li>");
document.writeln("		<li><span>Image 04</span></li>");
document.writeln("	</ul>");
document.writeln("	<div class=\'banner_content\'>");
document.writeln("		<h2>飓跃网络</h2>");
document.writeln("		<h3>隱私，是我們最關心的事</h3>");
document.writeln("	</div>");
document.writeln("	<span class=\'button\'>立即使用</span>");
document.writeln("</div>");
document.writeln("</a></section>");
document.writeln("</body>");