document.writeln("<head>");
document.writeln("  <meta charset=\'utf-8\'>");
document.writeln("   <title>云鸟网络加速,上网优势</title>");
document.writeln("  <meta name=\'description\' content=\'云鸟加速,网游加速器\'>");
document.writeln("  <meta name=\'keywords\' content=\'云鸟加速,网游加速器\'>");
document.writeln("  <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, maximum-scale=1\'> ");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/bootstrap.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/animate.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/font-awesome.min.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/font.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/landing.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/app.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/style.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'shortcut icon\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/favicon.ico\'>");
document.writeln("  ");
document.writeln("  <!--[if lt IE 9]>");
document.writeln("    <script src=\'js/ie/html5shiv.js\'></script>");
document.writeln("    <script src=\'js/ie/respond.min.js\'></script>");
document.writeln("    <script src=\'js/ie/excanvas.js\'></script>");
document.writeln("  <![endif]-->");
document.writeln("  <style>");
document.writeln("*{margin:0;padding:0;list-style-type:none;}");
document.writeln("a,img{border:0;}");
document.writeln("/* side */");
document.writeln(".side{position:fixed;width:54px;height:275px;right:0;top:214px;z-index:100;}");
document.writeln(".side ul li{width:54px;height:54px;float:left;position:relative;border-bottom:1px solid #444;}");
document.writeln(".side ul li .sidebox{position:absolute;width:54px;height:54px;top:0;right:0;transition:all 0.3s;background:#000;opacity:0.8;filter:Alpha(opacity=80);color:#fff;font:14px/54px \'微软雅黑\';overflow:hidden;}");
document.writeln(".side ul li .sidetop{width:54px;height:54px;line-height:54px;display:inline-block;background:#000;opacity:0.8;filter:Alpha(opacity=80);transition:all 0.3s;}");
document.writeln(".side ul li .sidetop:hover{background:#ae1c1c;opacity:1;filter:Alpha(opacity=100);}");
document.writeln(".side ul li img{float:left;}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("  	<!-- QQ客服begin -->");
document.writeln("<div class=\'side\'>");
document.writeln("	<ul>");
document.writeln("		<li><a href=\'/clientarea.php\'><div class=\'sidebox\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird//home/kf/img/side_icon01.png\'>会员中心</div></a></li>");
document.writeln("	  <li><a href=\'/register.php\'><div class=\'sidebox\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/home/kf/img/side_icon02.png\'>用户注册</div></a></li>");
document.writeln("	  <li><a href=\'https://t.me/cloudinbird\' ><div class=\'sidebox\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird//home/kf/img/side_icon04.png\'>联系客服</div></a></li>");
document.writeln("	  <li style=\'border:none;\'><a href=\'javascript:goTop();\' class=\'sidetop\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird//home/kf/img/side_icon05.png\'></a></li>");
document.writeln("  </ul>");
document.writeln("</div>");
document.writeln("<script src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/home/kf/jquery.min.js\'></script>	");
document.writeln("<script>");
document.writeln("$(function(){");
document.writeln("	$(\'.side ul li\').hover(function(){");
document.writeln("		$(this).find(\'.sidebox\').stop().animate({\'width\':\'124px\'},200).css({\'opacity\':\'1\',\'filter\':\'Alpha(opacity=100)\',\'background\':\'#ae1c1c\'})	");
document.writeln("	},function(){");
document.writeln("		$(this).find(\'.sidebox\').stop().animate({\'width\':\'54px\'},200).css({\'opacity\':\'0.8\',\'filter\':\'Alpha(opacity=80)\',\'background\':\'#000\'})	");
document.writeln("	});");
document.writeln("});");
document.writeln("//回到顶部函数");
document.writeln("function goTop(){");
document.writeln("	$(\'html,body\').animate({\'scrollTop\':0},300);");
document.writeln("}");
document.writeln("</script>");
document.writeln("<!-- QQ客服end -->");
document.writeln("  <!-- header -->");
document.writeln("  <header id=\'header\' class=\'navbar navbar-fixed-top bg-white box-shadow b-b b-light affix-top\' data-spy=\'affix\' data-offset-top=\'1\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'navbar-header\'>        ");
document.writeln("        <a href=\'/\' class=\'navbar-brand\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/logo.png\' class=\'m-r-sm\'><span class=\'text-muted\'>云鸟网络加速</span></a>");
document.writeln("        <button class=\'btn btn-link visible-xs\' type=\'button\' data-toggle=\'collapse\' data-target=\'.navbar-collapse\'>");
document.writeln("          <i class=\'fa fa-bars\'></i>");
document.writeln("        </button>");
document.writeln("      </div>");
document.writeln("      <div class=\'collapse navbar-collapse\'>");
document.writeln("        <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("          <li class=\'active\'>");
document.writeln("            <a href=\'index.php\'>网站首页</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <!--");
document.writeln("            <a href=\'Client.php\'>客户端下载</a>");
document.writeln("          </li>		  ");
document.writeln("          <li>");
document.writeln("            <a href=\'Course.php\'>使用教程</a>");
document.writeln("          </li>");
document.writeln("          ");
document.writeln("          <li>");
document.writeln("            <a href=\'clause.php\'>服务条款</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("          	<a href=\'buy.php\'>产品选择</a>");
document.writeln("          </li>");
document.writeln("			-->");
document.writeln("            <li>");
document.writeln("          	<a href=\'/cart.php\'>产品选择</a>");
document.writeln("          </li>");
document.writeln("		  <li>");
document.writeln("          	<a href=\'/affiliates.php\'>获得免费VIP套餐</a>");
document.writeln("          </li>");
document.writeln("		    <li>");
document.writeln("            <div class=\'m-t-sm\'> <a href=\'clientarea.php\' class=\'btn btn-warning btn-sm m-l\'>会员中心</a><a href=\'register.php\' class=\'btn btn-sm btn-success m-l\'><strong>用户注册</strong></a>  </div>");
document.writeln("          </li>");
document.writeln("		   <li>");
document.writeln("		      <br>");
document.writeln("		   </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </header>");
document.writeln("         ");
document.writeln("  <!-- / header -->");
document.writeln("");
document.writeln("<section id=\'content\'>");
document.writeln("	  <div class=\'bg-primary dk\'>");
document.writeln("      <div class=\'text-center wrapper\'>");
document.writeln("        <div class=\'m-t-xl m-b-xl\'>");
document.writeln("          <div class=\'text-uc h1 font-bold inline\'>");
document.writeln("            <div class=\'pull-left m-r-sm text-white\'>云鸟网络加速的优势 <span class=\'font-thin text-muted\'>很</span></div>");
document.writeln("            <div class=\'carousel slide carousel-fade inline auto aside text-left pull-left pull-none-xs\' data-interval=\'2000\'>");
document.writeln("                <div class=\'carousel-inner\'>");
document.writeln("                  <div class=\'item text-warning next left\'>");
document.writeln("                    快速");
document.writeln("                  </div>");
document.writeln("                  <div class=\'item text-dark\'>");
document.writeln("                    稳定");
document.writeln("                  </div>");
document.writeln("                  <div class=\'item active left\'>");
document.writeln("                    智能");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'h4 text-muted m-t-sm\'>目前最快、最稳定、最智能的跨域科学上网方式，是替代传统加速的最佳选择！</div>");
document.writeln("        </div>");
document.writeln("				<p class=\'text-center m-b-xl\'>");
document.writeln("          <a href=\'clientarea.php\' class=\'btn btn-lg btn-dark m-sm\'>登陆使用</a>");
document.writeln("          <a href=\'register.php\' class=\'btn btn-lg btn-warning b-white bg-empty m-sm\'>注册账户</a>");
document.writeln("        </p>");
document.writeln("		 ");
document.writeln("      </div>");
document.writeln("      <div class=\'padder\'>");
document.writeln("        <div class=\'hbox\'>");
document.writeln("          <aside class=\'col-md-3 v-bottom text-right\'>");
document.writeln("            <div class=\'hidden-sm hidden-xs\'>");
document.writeln("              <section class=\'panel bg-dark inline m-b-n-lg m-r-n-lg aside-sm no-border device phone animated fadeInLeftBig\'>");
document.writeln("                <header class=\'panel-heading text-center\'>");
document.writeln("                  <i class=\'fa fa-minus fa-2x m-b-n-xs block\'></i>");
document.writeln("                </header>");
document.writeln("                <div>");
document.writeln("                  <div class=\'m-l-xs m-r-xs\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/phone-2.png\' class=\'img-full\'>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("              </section>");
document.writeln("            </div>");
document.writeln("          </aside>");
document.writeln("          <aside class=\'col-sm-10 col-md-6\'>");
document.writeln("            <section class=\'panel bg-dark m-b-n-lg no-border device animated fadeInUp\'>");
document.writeln("              <header class=\'panel-heading text-left\'>");
document.writeln("                <i class=\'fa fa-circle fa-fw\'></i>");
document.writeln("                <i class=\'fa fa-circle fa-fw\'></i>");
document.writeln("                <i class=\'fa fa-circle fa-fw\'></i>");
document.writeln("              </header>");
document.writeln("              <img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/main.png\' class=\'img-full\'>");
document.writeln("            </section>");
document.writeln("          </aside>");
document.writeln("          <aside class=\'col-md-3 v-bottom\'>");
document.writeln("            <div class=\'hidden-sm hidden-xs\'>");
document.writeln("              <section class=\'panel bg-light m-b-n-lg m-l-n-lg aside no-border device phone animated fadeInRightBig\'>");
document.writeln("                <header class=\'panel-heading text-center\'>");
document.writeln("                  <i class=\'fa fa-minus fa-2x text-white m-b-n-xs block\'></i>");
document.writeln("                </header>");
document.writeln("                <div class=\'\'>");
document.writeln("                  <div class=\'m-l-xs m-r-xs\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/phone-1.png\' class=\'img-full\'>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("              </section>");
document.writeln("            </div>");
document.writeln("          </aside>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <div class=\'dker pos-rlt\'>");
document.writeln("        <div class=\'container wrapper\'>");
document.writeln("          <div class=\'m-t-lg m-b-lg text-center\'>");
document.writeln("            所有线路充分优化，达到最佳的状态，快速而不失稳定,给您高品质的上网体验.            ");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("	    <div id=\'about\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'m-t-xl m-b-xl text-center wrapper\'>");
document.writeln("          <h3>世界网络触手可及,秒开加速无需等待</h3>");
document.writeln("          <p class=\'text-muted\'>云中飞鸟带您飞往世界的每一处,世界无国界.</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'row m-t-xl m-b-xl text-center\'>");
document.writeln("          <div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("            <p class=\'h3 m-b-lg\'>");
document.writeln("              <i class=\'fa fa-check fa-3x text-info\'></i>");
document.writeln("            </p>");
document.writeln("            <div class=\'\'>");
document.writeln("              <h4 class=\'m-t-none\'>安全高效</h4>");
document.writeln("              <p class=\'text-muted m-t-lg\'>全站采用HTTPS加密，账号采用AES加密方式在体验超快的<br>浏览速度的同时也可以对<br>您真实的IP和地理位置等身份信息做到很好的保护。</p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'600\'>");
document.writeln("            <p class=\'h3 m-b-lg\'>");
document.writeln("              <i class=\'fa fa-globe fa-3x text-info\'></i>");
document.writeln("            </p>");
document.writeln("            <div class=\'\'>");
document.writeln("              <h4 class=\'m-t-none\'>快速稳定</h4>");
document.writeln("              <p class=\'text-muted m-t-lg\'>全自动均匀负载，Azure 美国、日本、香港、新加坡 节点极速体验<br>都是扯淡，没钱只有美国俩线路</p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'900\'>");
document.writeln("            <p class=\'h3 m-b-lg\'>");
document.writeln("              <i class=\'fa fa-comments fa-3x text-info\'></i>");
document.writeln("            </p>");
document.writeln("            <div class=\'\'>");
document.writeln("              <h4 class=\'m-t-none\'>客服支持</h4>");
document.writeln("              <p class=\'text-muted m-t-lg\'>7*24人工服务，远程技术支持，工作时间快速回复解决<br>每位用户使用过程中各种问题<br>看我心情回复，就我一人维护你以为啊！</p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("	");
document.writeln("	<section id=\'content\'>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'container m-t-lg m-b-lg\'>");
document.writeln("			<div class=\'row\'>");
document.writeln("        <div class=\'col-sm-12 text-center\'>");
document.writeln("<div class=\'blog-post\'>		              	");
document.writeln("            <div class=\'post-item\'>");
document.writeln("            	<div class=\'post-media\'>");
document.writeln("            		<section class=\'panel bg-primary dk m-b-none\'>");
document.writeln("                  <div class=\'carousel auto slide panel-body\' id=\'c-fade\'>      ");
document.writeln("                        <div class=\'item active text-center\'>");
document.writeln("                     <span class=\'h1\'>网络加速产品选择</span>                       ");
document.writeln("                      </div>                    ");
document.writeln("                  </div> ");
document.writeln("                </section>");
document.writeln("            	</div>");
document.writeln("				");
document.writeln("				");
document.writeln("<h2 class=\'post-title\'>加速节点宽带速度均为共享1000M端口,切勿访问违反国家法律的网站</h2>");
document.writeln("");
document.writeln("	<!-- tonghost start -->");
document.writeln("	<div class=\'about-skill-area\'>");
document.writeln("                    <div class=\'container\'>");
document.writeln("                        <div class=\'dt-sc-margin50\'></div>");
document.writeln("                        <!-- **dt-sc-pricing-table - Starts** -->");
document.writeln("                        <div class=\'dt-sc-pricing-table\'>");
document.writeln("                        ");
document.writeln("                            <div class=\'column dt-sc-one-fourth first\'>");
document.writeln("                                <!-- **dt-sc-pr-tb-col - Starts** -->");
document.writeln("                                <div class=\'dt-sc-pr-tb-col type3\'>");
document.writeln("                                    <!-- **dt-sc-tb-header - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-tb-header\'>");
document.writeln("                                        <!-- **dt-sc-price - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-price\'>");
document.writeln("                                            <div class=\'dt-sc-price-content\'>");
document.writeln("                                            	<h2> $0.00美元 </h2>");
document.writeln("                                            	<span>/ 7天</span>");
document.writeln("                                            </div>");
document.writeln("                                        </div> <!-- **dt-sc-price - Ends** -->");
document.writeln("                                        <!-- **dt-sc-tb-title - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-tb-title\'>");
document.writeln("                                            <h5> 免费套餐 </h5>");
document.writeln("                                        </div> <!-- **dt-sc-tb-title - Ends** -->");
document.writeln("                                    </div><!-- **dt-sc-tb-header - Ends** -->");
document.writeln("                                    <ul class=\'dt-sc-tb-content\'>");
document.writeln("                                        <li> <span class=\'fa fa-hdd-o\'></span><strong>流量上限 </strong> 1G</li>");
document.writeln("										<li><span class=\'highlight-red\'>普通线路</span></li>");
document.writeln("                                        <li> <span class=\'fa fa-bell\'></span><strong>系统支持 </strong> Win / Mac / Android / iPhone iPad / PS / Xbox</li>");
document.writeln("                                        <li> <span class=\'fa fa-upload\'></span><strong>适用人群：</strong> 体验加速消费者</li>");
document.writeln("                                        <li><span class=\'red\'>不予退款</span> 随时无缝升级</li>");
document.writeln("										<li> <span <strong>(7天)</strong> 0美元<br></li>");
document.writeln("										<li> <span <strong>季付</strong> 不支持<br></li>");
document.writeln("										<li> <span <strong>半年</strong> 不支持<br></li>");
document.writeln("										<li> <span <strong>年付</strong> 不支持<br></li>");
document.writeln("										");
document.writeln("                                    </ul>");
document.writeln("                                    <div class=\'dt-sc-buy-now\'>");
document.writeln("                                        <a class=\'dt-sc-button small\' href=\'/cart.php?a=add&pid=1\'> 立即订购 <span class=\'fa fa-arrow-right\'></span> </a>");
document.writeln("                                    </div> <!-- **dt-sc-buy-now - Ends** -->");
document.writeln("                                    ");
document.writeln("                                </div> <!-- **dt-sc-pr-tb-col - Ends** -->");
document.writeln("                            </div> ");
document.writeln("                       ");
document.writeln("                        ");
document.writeln("                            <div class=\'column dt-sc-one-fourth\'>");
document.writeln("                                    <!-- **dt-sc-pr-tb-col - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-pr-tb-col type3\'>");
document.writeln("                                    <!-- **dt-sc-tb-header - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-tb-header\'>");
document.writeln("                                        <!-- **dt-sc-price - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-price\'>");
document.writeln("                                            <div class=\'dt-sc-price-content\'>");
document.writeln("                                            	<h2> $10.00美元 </h2>");
document.writeln("                                            	<span>/ 月</span>");
document.writeln("                                            </div>");
document.writeln("                                        </div> <!-- **dt-sc-price - Ends** -->");
document.writeln("                                        <!-- **dt-sc-tb-title - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-tb-title\'>");
document.writeln("                                            <h5> 普通VIP套餐 </h5>");
document.writeln("                                        </div> <!-- **dt-sc-tb-title - Ends** -->");
document.writeln("                                    </div><!-- **dt-sc-tb-header - Ends** -->");
document.writeln("                                    <ul class=\'dt-sc-tb-content\'>");
document.writeln("                                        <li> <span class=\'fa fa-hdd-o\'></span><strong>流量上限 </strong> 60G</li>");
document.writeln("										<li><span class=\'highlight-red\'>普通VIP线路</span></li>");
document.writeln("                                        <li> <span class=\'fa fa-bell\'></span><strong>系统支持 </strong> Win / Mac / Android / iPhone iPad / PS / Xbox</li>");
document.writeln("                                        <li> <span class=\'fa fa-upload\'></span><strong>适用人群：</strong> 查询海外学习资料</li>");
document.writeln("                                        <li><span class=\'red\'>3天无条件退款</span> 随时无缝升级</li>");
document.writeln("										<li> <span <strong>月付</strong> 10美元<br></li>");
document.writeln("										<li> <span <strong>季付</strong> 30美元<br></li>");
document.writeln("										<li> <span <strong>半年</strong> 60美元<br></li>");
document.writeln("										<li> <span <strong>年付</strong> 120美元<br></li>");
document.writeln("										");
document.writeln("                                    </ul>");
document.writeln("                                    <div class=\'dt-sc-buy-now\'>");
document.writeln("                                        <a class=\'dt-sc-button small\' href=\'/cart.php?a=add&pid=2\'> 立即订购 <span class=\'fa fa-arrow-right\'></span> </a>");
document.writeln("                                    </div> <!-- **dt-sc-buy-now - Ends** -->");
document.writeln("                                    ");
document.writeln("                                </div> <!-- **dt-sc-pr-tb-col - Ends** -->");
document.writeln("                                </div> ");
document.writeln("                                ");
document.writeln("                                <div class=\'column dt-sc-one-fourth\'>");
document.writeln("                                    <!-- **dt-sc-pr-tb-col - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-pr-tb-col type3\'>");
document.writeln("                                    <!-- **dt-sc-tb-header - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-tb-header\'>");
document.writeln("                                        <!-- **dt-sc-price - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-price\'>");
document.writeln("                                            <div class=\'dt-sc-price-content\'>");
document.writeln("                                            	<h2> $20.00美元 </h2>");
document.writeln("                                            	<span>/ 月</span>");
document.writeln("                                            </div>");
document.writeln("                                        </div> <!-- **dt-sc-price - Ends** -->");
document.writeln("                                        <!-- **dt-sc-tb-title - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-tb-title\'>");
document.writeln("                                            <h5> 标准VIP套餐 </h5>");
document.writeln("                                        </div> <!-- **dt-sc-tb-title - Ends** -->");
document.writeln("                                    </div><!-- **dt-sc-tb-header - Ends** -->");
document.writeln("                                    <ul class=\'dt-sc-tb-content\'>");
document.writeln("                                        <li> <span class=\'fa fa-hdd-o\'></span><strong>流量上限 </strong> 120G</li>");
document.writeln("										<li><span class=\'highlight-red\'>标准VIP线路</span></li>");
document.writeln("                                        <li> <span class=\'fa fa-bell\'></span><strong>系统支持 </strong> Win / Mac / Android / iPhone iPad / PS / Xbox</li>");
document.writeln("                                        <li> <span class=\'fa fa-upload\'></span><strong>适用人群：</strong> 查询海外资料,外企人员</li>");
document.writeln("                                        <li><span class=\'red\'>3天无条件退款</span> 随时无缝升级</li>");
document.writeln("										<li> <span <strong>月付</strong> 20美元<br></li>");
document.writeln("										<li> <span <strong>季付</strong> 60美元<br></li>");
document.writeln("										<li> <span <strong>半年</strong> 120美元<br></li>");
document.writeln("										<li> <span <strong>年付</strong> 240美元<br></li>");
document.writeln("										");
document.writeln("                                    </ul>");
document.writeln("                                    <div class=\'dt-sc-buy-now\'>");
document.writeln("                                        <a class=\'dt-sc-button small\' href=\'/cart.php?a=add&pid=3\'> 立即订购 <span class=\'fa fa-arrow-right\'></span> </a>");
document.writeln("                                    </div> <!-- **dt-sc-buy-now - Ends** -->");
document.writeln("                                    ");
document.writeln("                                </div> <!-- **dt-sc-pr-tb-col - Ends** -->");
document.writeln("                                </div> ");
document.writeln("                                ");
document.writeln("                                <div class=\'column dt-sc-one-fourth\'>");
document.writeln("                                    <!-- **dt-sc-pr-tb-col - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-pr-tb-col type3\'>");
document.writeln("                                    <!-- **dt-sc-tb-header - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-tb-header\'>");
document.writeln("                                        <!-- **dt-sc-price - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-price\'>");
document.writeln("                                            <div class=\'dt-sc-price-content\'>");
document.writeln("                                            	<h2> $40.00美元 </h2>");
document.writeln("                                            	<span>/ 月</span>");
document.writeln("                                            </div>");
document.writeln("                                        </div> <!-- **dt-sc-price - Ends** -->");
document.writeln("                                        <!-- **dt-sc-tb-title - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-tb-title\'>");
document.writeln("                                            <h5> 高级VIP套餐 </h5>");
document.writeln("                                        </div> <!-- **dt-sc-tb-title - Ends** -->");
document.writeln("                                    </div><!-- **dt-sc-tb-header - Ends** -->");
document.writeln("                                    <ul class=\'dt-sc-tb-content\'>");
document.writeln("                                        <li> <span class=\'fa fa-hdd-o\'></span><strong>流量上限 </strong> 不限流量嗨到爆</li>");
document.writeln("										<li><span class=\'highlight-red\'>高级VIP线路</span></li>");
document.writeln("                                        <li> <span class=\'fa fa-bell\'></span><strong>系统支持 </strong> Win / Mac / Android / iPhone iPad / PS / Xbox</li>");
document.writeln("                                        <li> <span class=\'fa fa-upload\'></span><strong>适用人群：</strong> 海外游戏加速,外企,IT技术</li>");
document.writeln("                                        <li><span class=\'red\'>3天无条件退款</span> 随时无缝升级</li>");
document.writeln("										<li> <span <strong>月付</strong> 40美元<br></li>");
document.writeln("										<li> <span <strong>季付</strong> 120美元<br></li>");
document.writeln("										<li> <span <strong>半年</strong> 240美元<br></li>");
document.writeln("										<li> <span <strong>年付</strong> 480美元<br></li>");
document.writeln("										");
document.writeln("                                    </ul>");
document.writeln("                                    <div class=\'dt-sc-buy-now\'>");
document.writeln("                                        <a class=\'dt-sc-button small\' href=\'/cart.php?a=add&pid=4\'> 立即订购 <span class=\'fa fa-arrow-right\'></span> </a>");
document.writeln("                                    </div> <!-- **dt-sc-buy-now - Ends** -->");
document.writeln("                                    ");
document.writeln("                                </div> <!-- **dt-sc-pr-tb-col - Ends** -->");
document.writeln("                                </div> ");
document.writeln("                        ");
document.writeln("                        </div> <!-- **dt-sc-pricing-table - Ends** -->");
document.writeln("                        ");
document.writeln("                    </div>");
document.writeln("");
document.writeln("	</div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	</div></div></section>");
document.writeln("	");
document.writeln("	");
document.writeln("	    <div id=\'responsive\' class=\'bg-dark\'>");
document.writeln("      <div class=\'text-center\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("          <div class=\'m-t-xl m-b-xl wrapper\'>");
document.writeln("            <h3 class=\'text-white\'>稳定运行于主流的Windows / iOS / Android / Mac OS 等操作系统</h3>");
document.writeln("            <p>深受广大IT程序员、学术研究员、视频爱好者、外贸企业等需访问海外人士的喜爱.</p>");
document.writeln("          </div>");
document.writeln("          <div class=\'row m-t-xl m-b-xl\'>");
document.writeln("		    <div class=\'col-sm-3 wrapper-xl\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("              <p class=\'text-center h2 m-b-lg m-t-lg\'>");
document.writeln("                <span class=\'fa-stack fa-2x\'>");
document.writeln("				<a href=\'Client.php\'>");
document.writeln("                  <i class=\'fa fa-circle fa-stack-2x text-dark\'></i>");
document.writeln("                  <i class=\'fa fa-apple fa-stack-1x text-muted\'></i>");
document.writeln("                </a></span><a href=\'Client.php\'>");
document.writeln("              </a></p><a href=\'Client.php\'>");
document.writeln("              <span class=\'text-primary text-ul\'>iOS</span></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 wrapper-xl\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("              <p class=\'text-center h2 m-b-lg m-t-lg\'>");
document.writeln("                <span class=\'fa-stack fa-2x\'>");
document.writeln("				<a href=\'Client.php\'>");
document.writeln("                  <i class=\'fa fa-circle fa-stack-2x text-dark\'></i>");
document.writeln("                  <i class=\'fa fa-android fa-stack-1x text-muted\'></i>");
document.writeln("                </a></span><a href=\'Client.php\'>");
document.writeln("              </a></p><a href=\'Client.php\'>");
document.writeln("              <span class=\'text-primary text-ul\'>Android</span></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 wrapper-xl\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("              <p class=\'text-center h2 m-b-lg m-t-lg\'>");
document.writeln("                <span class=\'fa-stack fa-2x\'>");
document.writeln("				<a href=\'Client.php\'>");
document.writeln("                  <i class=\'fa fa-circle fa-stack-2x text-dark\'></i>");
document.writeln("                  <i class=\'fa fa-windows fa-stack-1x text-muted\'></i>");
document.writeln("                </a></span><a href=\'Client.php\'>");
document.writeln("              </a></p><a href=\'Client.php\'>");
document.writeln("              <span class=\'text-primary text-ul\'>Windows</span></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 wrapper-xl\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("              <p class=\'text-center h2 m-b-lg m-t-lg\'>");
document.writeln("                <span class=\'fa-stack fa-2x\'>");
document.writeln("				<a href=\'Client.php\'>");
document.writeln("                  <i class=\'fa fa-circle fa-stack-2x text-dark\'></i>");
document.writeln("                  <i class=\'fa fa-laptop fa-stack-1x text-muted text-md\'></i>");
document.writeln("                </a></span><a href=\'Client.php\'>");
document.writeln("              </a></p><a href=\'Client.php\'>");
document.writeln("              <span class=\'text-primary text-ul\'>Mac</span></a>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div> ");
document.writeln("</section>");
document.writeln("<footer id=\'footer\'>");
document.writeln("  	<div class=\'bg-primary text-center\'>");
document.writeln("      <div class=\'container wrapper\'>");
document.writeln("        <div class=\'m-t-xl m-b\'>");
document.writeln("          马上点击下方开始您的稳定高速上网体验.");
document.writeln("          <a href=\'clientarea.php\' class=\'btn btn-lg btn-dark b-white bg-empty m-sm\'>登陆使用</a>");
document.writeln("          <a href=\'register.php\' class=\'btn btn-lg btn-warning b-white bg-empty m-sm\'>注册账户</a>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <i class=\'fa fa-caret-down fa-4x text-primary m-b-n-lg block\'></i>");
document.writeln("	</div>");
document.writeln("  ");
document.writeln("	<div class=\'bg-dark dker wrapper\'>");
document.writeln("		<div class=\'container text-center m-t-lg\'>");
document.writeln("			<div class=\'row m-t-xl m-b-xl\'>");
document.writeln("				<div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("					<i class=\'fa fa-bullhorn fa-3x icon-muted\'></i>");
document.writeln("					<h5 class=\'text-uc m-b m-t-lg\'>免责声明</h5>");
document.writeln("					<p class=\'text-sm\'>使用 <a href=\'index.php\' title=\'云鸟\'>[云鸟网络加速]</a> 请遵守当地法律 <br>");
document.writeln("						云鸟网络加速不承担因使用本站服务所发生的任何责任.");
document.writeln("             	</p>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInUp\' data-delay=\'600\'>");
document.writeln("					<i class=\'fa fa-ticket fa-3x icon-muted\'></i>");
document.writeln("					<h5 class=\'text-uc m-b m-t-lg\'>工单服务</h5>");
document.writeln("					<p class=\'text-sm\'><a href=\'clientarea.php\'>在线工单技术支持,最快回复</a><br>在使用本站服务过程中有任何问题欢迎提交工单.</p>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInRight\' data-delay=\'900\'>");
document.writeln("					<i class=\'fa fa-desktop fa-3x icon-muted\'></i>");
document.writeln("					<h5 class=\'text-uc m-b m-t-lg\'>远程支持</h5>");
document.writeln("					<p class=\'text-sm\'></p><div class=\'follow-us\'>Telegram：<a href=\'https://t.me/cloudinbird\'>cloudinbird</a><br><p></p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<br>");
document.writeln("			<div class=\'m-t-xl m-b-xl\'>");
document.writeln("				<p> ");
document.writeln("            <a href=\'index.php#content\' data-jump=\'true\' class=\'btn btn-icon btn-rounded btn-dark b-dark bg-empty m-sm text-muted\'><i class=\'fa fa-angle-up\'></i></a>");
document.writeln("          	</p>");
document.writeln("			</div>");
document.writeln("			<div class=\'m-t-xl m-b-xl\'>");
document.writeln("				<p> ");
document.writeln("            Powered By<a href=\'/index.php\' class=\'b-dark bg-empty m-sm text-muted\'>云鸟网络加速</a>");
document.writeln("          	</p>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</footer>");
document.writeln("");
document.writeln("   <script src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/js/jquery.min.js\'></script>");
document.writeln("  <script src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/js/bootstrap.js\'></script>");
document.writeln("  <script src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/js/app.js\'></script>");
document.writeln("  </body>");