document.writeln("<head>");
document.writeln("  <meta charset=\'utf-8\'>");
document.writeln("  <title>Cloudbird Network, Internet Advantage</title>");
document.writeln("  <meta name=\'description\' content=\'CLOUDBIRD NETWORK, Online Game Accelerator\'>");
document.writeln("  <meta name=\'keywords\' content=\'CLOUDBIRD NETWORK, Online Game Accelerator\'>");
document.writeln("  <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, maximum-scale=1\'> ");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/bootstrap.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/animate.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/font-awesome.min.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/font.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/landing.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/app.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/css/style.css\' type=\'text/css\'>");
document.writeln("  <link rel=\'shortcut icon\' href=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/favicon.ico\'>");
document.writeln("  ");
document.writeln("  <!--Start of Tawk.to Script-->");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();");
document.writeln("(function(){");
document.writeln("var s1=document.createElement(\'script\'),s0=document.getElementsByTagName(\'script\')[0];");
document.writeln("s1.async=true;");
document.writeln("s1.src=\'https://embed.tawk.to/5ab4b8a94b401e45400dfbb0/default\';");
document.writeln("s1.charset=\'UTF-8\';");
document.writeln("s1.setAttribute(\'crossorigin\',\'*\');");
document.writeln("s0.parentNode.insertBefore(s1,s0);");
document.writeln("})();");
document.writeln("</script>");
document.writeln("  ");
document.writeln("<!--End of Tawk.to Script-->");
document.writeln("  ");
document.writeln("  <!--[if lt IE 9]>");
document.writeln("    <script src=\'js/ie/html5shiv.js\'></script>");
document.writeln("    <script src=\'js/ie/respond.min.js\'></script>");
document.writeln("    <script src=\'js/ie/excanvas.js\'></script>");
document.writeln("  <![endif]-->");
document.writeln("  <style>");
document.writeln("*{margin:0;padding:0;list-style-type:none;}");
document.writeln("a,img{border:0;}");
document.writeln("/* side */");
document.writeln(".side{position:fixed;width:54px;height:275px;right:0;top:214px;z-index:100;}");
document.writeln(".side ul li{width:54px;height:54px;float:left;position:relative;border-bottom:1px solid #444;}");
document.writeln(".side ul li .sidebox{position:absolute;width:54px;height:54px;top:0;right:0;transition:all 0.3s;background:#000;opacity:0.8;filter:Alpha(opacity=80);color:#fff;font:14px/54px \'微软雅黑\';overflow:hidden;}");
document.writeln(".side ul li .sidetop{width:54px;height:54px;line-height:54px;display:inline-block;background:#000;opacity:0.8;filter:Alpha(opacity=80);transition:all 0.3s;}");
document.writeln(".side ul li .sidetop:hover{background:#ae1c1c;opacity:1;filter:Alpha(opacity=100);}");
document.writeln(".side ul li img{float:left;}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("  	<!-- QQ客服begin -->");
document.writeln("<div class=\'side\'>");
document.writeln("	<ul>");
document.writeln("		<li><a href=\'/clientarea.php\'><div class=\'sidebox\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/home/kf/img/side_icon01.png\'>Member Centre</div></a></li>");
document.writeln("	  <li><a href=\'/register.php\'><div class=\'sidebox\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/home/kf/img/side_icon02.png\'>User registration</div></a></li>");
document.writeln("	  <li><a href=\'https://t.me/cloudinbird\' ><div class=\'sidebox\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/home/kf/img/side_icon04.png\'>Contact Customer Service</div></a></li>");
document.writeln("	  <li style=\'border:none;\'><a href=\'javascript:goTop();\' class=\'sidetop\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/home/kf/img/side_icon05.png\'></a></li>");
document.writeln("  </ul>");
document.writeln("</div>");
document.writeln("<script src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/home/kf/jquery.min.js\'></script>	");
document.writeln("<script>");
document.writeln("$(function(){");
document.writeln("	$(\'.side ul li\').hover(function(){");
document.writeln("		$(this).find(\'.sidebox\').stop().animate({\'width\':\'124px\'},200).css({\'opacity\':\'1\',\'filter\':\'Alpha(opacity=100)\',\'background\':\'#ae1c1c\'})	");
document.writeln("	},function(){");
document.writeln("		$(this).find(\'.sidebox\').stop().animate({\'width\':\'54px\'},200).css({\'opacity\':\'0.8\',\'filter\':\'Alpha(opacity=80)\',\'background\':\'#000\'})	");
document.writeln("	});");
document.writeln("    $(\'.language-class\').hover(function(){");
document.writeln("    	$(\'.lang-list\').css(\'display\',\'block\');");
document.writeln("      $(\'.lang-list\').delay(800).fadeIn();");
document.writeln("    },function(){");
document.writeln("      	//$(\'.lang-list\').delay(900).fadeIn();");
document.writeln("    	$(\'.lang-list\').css(\'display\',\'none\');");
document.writeln("    });");
document.writeln("});");
document.writeln("//回到顶部函数");
document.writeln("function goTop(){");
document.writeln("	$(\'html,body\').animate({\'scrollTop\':0},300);");
document.writeln("}");
document.writeln("</script>");
document.writeln("  <style>");
document.writeln("    .language-class{");
document.writeln("    	position: relative;");
document.writeln("      text-");
document.writeln("    }");
document.writeln("    .lang-list{");
document.writeln("    	position: absolute;");
document.writeln("        top: 36px;");
document.writeln("    	left: 0;");
document.writeln("      	text-align: center;");
document.writeln("        background: #FFF;");
document.writeln("        width:100px;");
document.writeln("        ");
document.writeln("        display: none;");
document.writeln("    }");
document.writeln("    ul.lang-list li {");
document.writeln("        height: 35px;");
document.writeln("        border-bottom: 1px solid gray;");
document.writeln("        line-height:35px;");
document.writeln("      ");
document.writeln("    }");
document.writeln("    .language-class:hover {");
document.writeln("        cursor: pointer;");
document.writeln("    }");
document.writeln("    ");
document.writeln("    .niubi-class {");
document.writeln("            float: right;");
document.writeln("            position: absolute;");
document.writeln("            right: 25px;");
document.writeln("            top: 9px;");
document.writeln("            width: 100px;");
document.writeln("            height: 37px;");
document.writeln("	        line-height:37px;");
document.writeln("            text-align: center;");
document.writeln("            background: #8cdd87;");
document.writeln("    }");
document.writeln("  </style>");
document.writeln("<!-- QQ客服end -->");
document.writeln("  <!-- header -->");
document.writeln("  <header id=\'header\' class=\'navbar navbar-fixed-top bg-white box-shadow b-b b-light affix-top\' data-spy=\'affix\' data-offset-top=\'1\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'navbar-header\'>        ");
document.writeln("        <a href=\'/\' class=\'navbar-brand\'><img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/logo.png\' class=\'m-r-sm\'><span class=\'text-muted\'>Cloudbird Network</span></a>");
document.writeln("        <button class=\'btn btn-link visible-xs\' type=\'button\' data-toggle=\'collapse\' data-target=\'.navbar-collapse\'>");
document.writeln("          <i class=\'fa fa-bars\'></i>");
document.writeln("        </button>");
document.writeln("      </div>");
document.writeln("      <div class=\'collapse navbar-collapse\'>");
document.writeln("        <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("          <li class=\'active\'>");
document.writeln("            <a href=\'index.php\'>Home page</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <!--          ");
document.writeln("          <li>");
document.writeln("            <a href=\'clause.php\'>Terms of Service</a>");
document.writeln("          </li>");
document.writeln("		");
document.writeln("          <li>");
document.writeln("          	<a href=\'buy.php\'>Product choice</a>");
document.writeln("          </li>");
document.writeln("		-->");
document.writeln("            <li>");
document.writeln("          	<a href=\'/cart.php\'>Product choice</a>");
document.writeln("          </li>");
document.writeln("          ");
document.writeln("		  <li>");
document.writeln("          	<a href=\'/affiliates.php\'>Get a free VIP package</a>");
document.writeln("          </li>");
document.writeln("		    <li>");
document.writeln("            <div class=\'m-t-sm\'> <a href=\'clientarea.php\' class=\'btn btn-warning btn-sm m-l\'>Member Centre</a><a href=\'register.php\' class=\'btn btn-sm btn-success m-l\'><strong>User registration</strong></a>  </div>");
document.writeln("          </li>");
document.writeln("           ");
document.writeln("		   <li>");
document.writeln("		      <br>");
document.writeln("		   </li>");
document.writeln("        </ul>");
document.writeln("        <!--");
document.writeln("        <div class=\'niubi-class\'>");
document.writeln("          <li class=\'language-class\'>");
document.writeln("          	<a href=\'javascript:;\' id=\'language\' >Language</a>");
document.writeln("             <ul class=\'lang-list\'>");
document.writeln("               <li><a href=\'index.php\'>English</a></li>");
document.writeln("               <li><a href=\'indexchina.php\'>简体中文</a></li>");
document.writeln("             </ul>");
document.writeln("          </li>");
document.writeln("        </div>");
document.writeln("        -->");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </header>");
document.writeln("         ");
document.writeln("  <!-- / header -->");
document.writeln("");
document.writeln("<section id=\'content\'>");
document.writeln("	  <div class=\'bg-primary dk\'>");
document.writeln("      <div class=\'text-center wrapper\'>");
document.writeln("        <div class=\'m-t-xl m-b-xl\'>");
document.writeln("          <div class=\'text-uc h1 font-bold inline\'>");
document.writeln("            <div class=\'pull-left m-r-sm text-white\'>Cloudbird Network Acceleration Advantage <span class=\'font-thin text-muted\'>very</span></div>");
document.writeln("            <div class=\'carousel slide carousel-fade inline auto aside text-left pull-left pull-none-xs\' data-interval=\'2000\'>");
document.writeln("                <div class=\'carousel-inner\'>");
document.writeln("                  <div class=\'item text-warning next left\'>");
document.writeln("                    fast");
document.writeln("                  </div>");
document.writeln("                  <div class=\'item text-dark\'>");
document.writeln("                    stable");
document.writeln("                  </div>");
document.writeln("                  <div class=\'item active left\'>");
document.writeln("                    intelligent");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'h4 text-muted m-t-sm\'>The fastest, most stable, and most intelligent cross-domain scientific Internet access is the best alternative to traditional acceleration.！</div>");
document.writeln("        </div>");
document.writeln("				<p class=\'text-center m-b-xl\'>");
document.writeln("          <a href=\'clientarea.php\' class=\'btn btn-lg btn-dark m-sm\'>Landing use</a>");
document.writeln("          <a href=\'register.php\' class=\'btn btn-lg btn-warning b-white bg-empty m-sm\'>register account</a>");
document.writeln("        </p>");
document.writeln("		 ");
document.writeln("      </div>");
document.writeln("      <div class=\'padder\'>");
document.writeln("        <div class=\'hbox\'>");
document.writeln("          <aside class=\'col-md-3 v-bottom text-right\'>");
document.writeln("            <div class=\'hidden-sm hidden-xs\'>");
document.writeln("              <section class=\'panel bg-dark inline m-b-n-lg m-r-n-lg aside-sm no-border device phone animated fadeInLeftBig\'>");
document.writeln("                <header class=\'panel-heading text-center\'>");
document.writeln("                  <i class=\'fa fa-minus fa-2x m-b-n-xs block\'></i>");
document.writeln("                </header>");
document.writeln("                <div>");
document.writeln("                  <div class=\'m-l-xs m-r-xs\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/phone-2.png\' class=\'img-full\'>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("              </section>");
document.writeln("            </div>");
document.writeln("          </aside>");
document.writeln("          <aside class=\'col-sm-10 col-md-6\'>");
document.writeln("            <section class=\'panel bg-dark m-b-n-lg no-border device animated fadeInUp\'>");
document.writeln("              <header class=\'panel-heading text-left\'>");
document.writeln("                <i class=\'fa fa-circle fa-fw\'></i>");
document.writeln("                <i class=\'fa fa-circle fa-fw\'></i>");
document.writeln("                <i class=\'fa fa-circle fa-fw\'></i>");
document.writeln("              </header>");
document.writeln("              <img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/main.png\' class=\'img-full\'>");
document.writeln("            </section>");
document.writeln("          </aside>");
document.writeln("          <aside class=\'col-md-3 v-bottom\'>");
document.writeln("            <div class=\'hidden-sm hidden-xs\'>");
document.writeln("              <section class=\'panel bg-light m-b-n-lg m-l-n-lg aside no-border device phone animated fadeInRightBig\'>");
document.writeln("                <header class=\'panel-heading text-center\'>");
document.writeln("                  <i class=\'fa fa-minus fa-2x text-white m-b-n-xs block\'></i>");
document.writeln("                </header>");
document.writeln("                <div class=\'\'>");
document.writeln("                  <div class=\'m-l-xs m-r-xs\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/images/phone-1.png\' class=\'img-full\'>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("              </section>");
document.writeln("            </div>");
document.writeln("          </aside>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <div class=\'dker pos-rlt\'>");
document.writeln("        <div class=\'container wrapper\'>");
document.writeln("          <div class=\'m-t-lg m-b-lg text-center\'>");
document.writeln("            All lines are fully optimized to achieve the best state, fast and stable, giving you a high quality internet experience.          ");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("	    <div id=\'about\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'m-t-xl m-b-xl text-center wrapper\'>");
document.writeln("          <h3>World network at your fingertips, seconds to accelerate without waiting</h3>");
document.writeln("          <p class=\'text-muted\'>Flying birds in the clouds take you to every part of the world. The world has no borders.</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'row m-t-xl m-b-xl text-center\'>");
document.writeln("          <div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("            <p class=\'h3 m-b-lg\'>");
document.writeln("              <i class=\'fa fa-check fa-3x text-info\'></i>");
document.writeln("            </p>");
document.writeln("            <div class=\'\'>");
document.writeln("              <h4 class=\'m-t-none\'>Safe and efficient</h4>");
document.writeln("              <p class=\'text-muted m-t-lg\'>The entire station uses HTTPS encryption, and the account uses AES encryption to experience ultra-fast<br>While browsing the speed, you can also<br>Your true IP and geographical location and other identity information do a good job of protection。</p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'600\'>");
document.writeln("            <p class=\'h3 m-b-lg\'>");
document.writeln("              <i class=\'fa fa-globe fa-3x text-info\'></i>");
document.writeln("            </p>");
document.writeln("            <div class=\'\'>");
document.writeln("              <h4 class=\'m-t-none\'>Fast and stable</h4>");
document.writeln("              <p class=\'text-muted m-t-lg\'>Fully automatic load, Azure USA, Japan, Hong Kong, Singapore<br>It\'s all nonsense. There\'s only money in the United States.</p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'900\'>");
document.writeln("            <p class=\'h3 m-b-lg\'>");
document.writeln("              <i class=\'fa fa-comments fa-3x text-info\'></i>");
document.writeln("            </p>");
document.writeln("            <div class=\'\'>");
document.writeln("              <h4 class=\'m-t-none\'>Customer support</h4>");
document.writeln("              <p class=\'text-muted m-t-lg\'>7*24 manual service, remote technical support, working time quick reply<br>Each user uses various issues in the process<br>Look at me and I feel like I\'m maintaining you.</p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("	");
document.writeln("	<section id=\'content\'>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'container m-t-lg m-b-lg\'>");
document.writeln("			<div class=\'row\'>");
document.writeln("        <div class=\'col-sm-12 text-center\'>");
document.writeln("<div class=\'blog-post\'>		              	");
document.writeln("            <div class=\'post-item\'>");
document.writeln("            	<div class=\'post-media\'>");
document.writeln("            		<section class=\'panel bg-primary dk m-b-none\'>");
document.writeln("                  <div class=\'carousel auto slide panel-body\' id=\'c-fade\'>      ");
document.writeln("                        <div class=\'item active text-center\'>");
document.writeln("                     <span class=\'h1\'>Network Acceleration Product Selection</span>                       ");
document.writeln("                      </div>                    ");
document.writeln("                  </div> ");
document.writeln("                </section>");
document.writeln("            	</div>");
document.writeln("				");
document.writeln("				");
document.writeln("<h2 class=\'post-title\'>Acceleration node broadband speed is shared 1000M port</h2>");
document.writeln("");
document.writeln("	<!-- tonghost start -->");
document.writeln("	<div class=\'about-skill-area\'>");
document.writeln("                    <div class=\'container\'>");
document.writeln("                        <div class=\'dt-sc-margin50\'></div>");
document.writeln("                        <!-- **dt-sc-pricing-table - Starts** -->");
document.writeln("                        <div class=\'dt-sc-pricing-table\'>");
document.writeln("                        ");
document.writeln("                            <div class=\'column dt-sc-one-fourth first\'>");
document.writeln("                                <!-- **dt-sc-pr-tb-col - Starts** -->");
document.writeln("                                <div class=\'dt-sc-pr-tb-col type3\'>");
document.writeln("                                    <!-- **dt-sc-tb-header - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-tb-header\'>");
document.writeln("                                        <!-- **dt-sc-price - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-price\'>");
document.writeln("                                            <div class=\'dt-sc-price-content\'>");
document.writeln("                                            	<h2> $0.00USD </h2>");
document.writeln("                                            	<span>/ 7day</span>");
document.writeln("                                            </div>");
document.writeln("                                        </div> <!-- **dt-sc-price - Ends** -->");
document.writeln("                                        <!-- **dt-sc-tb-title - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-tb-title\'>");
document.writeln("                                            <h5> Free meal</h5>");
document.writeln("                                        </div> <!-- **dt-sc-tb-title - Ends** -->");
document.writeln("                                    </div><!-- **dt-sc-tb-header - Ends** -->");
document.writeln("                                    <ul class=\'dt-sc-tb-content\'>");
document.writeln("                                        <li> <span class=\'fa fa-hdd-o\'></span><strong>Traffic cap </strong> 1G</li>");
document.writeln("										<li><span class=\'highlight-red\'>Ordinary line</span></li>");
document.writeln("                                        <li> <span class=\'fa fa-bell\'></span><strong>System Support </strong> Win / Mac / Android / iPhone iPad / PS / Xbox</li>");
document.writeln("                                        <li> <span class=\'fa fa-upload\'></span><strong>For people：</strong> Experience accelerated consumers</li>");
document.writeln("                                        <li><span class=\'red\'>No refund</span> Seamlessly upgrade at any time</li>");
document.writeln("										<li> <span <strong>(7day)</strong> 0USD<br></li>");
document.writeln("										<li> <span <strong>Season pay</strong> not support<br></li>");
document.writeln("										<li> <span <strong>Six months</strong> not support<br></li>");
document.writeln("										<li> <span <strong>annual fee</strong> not support<br></li>");
document.writeln("										");
document.writeln("                                    </ul>");
document.writeln("                                    <div class=\'dt-sc-buy-now\'>");
document.writeln("                                        <a class=\'dt-sc-button small\' href=\'/cart.php?a=add&pid=1\'> order now <span class=\'fa fa-arrow-right\'></span> </a>");
document.writeln("                                    </div> <!-- **dt-sc-buy-now - Ends** -->");
document.writeln("                                    ");
document.writeln("                                </div> <!-- **dt-sc-pr-tb-col - Ends** -->");
document.writeln("                            </div> ");
document.writeln("                       ");
document.writeln("                        ");
document.writeln("                            <div class=\'column dt-sc-one-fourth\'>");
document.writeln("                                    <!-- **dt-sc-pr-tb-col - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-pr-tb-col type3\'>");
document.writeln("                                    <!-- **dt-sc-tb-header - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-tb-header\'>");
document.writeln("                                        <!-- **dt-sc-price - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-price\'>");
document.writeln("                                            <div class=\'dt-sc-price-content\'>");
document.writeln("                                            	<h2> $10.00USD </h2>");
document.writeln("                                            	<span>/ month</span>");
document.writeln("                                            </div>");
document.writeln("                                        </div> <!-- **dt-sc-price - Ends** -->");
document.writeln("                                        <!-- **dt-sc-tb-title - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-tb-title\'>");
document.writeln("                                            <h5> Ordinary VIP </h5>");
document.writeln("                                        </div> <!-- **dt-sc-tb-title - Ends** -->");
document.writeln("                                    </div><!-- **dt-sc-tb-header - Ends** -->");
document.writeln("                                    <ul class=\'dt-sc-tb-content\'>");
document.writeln("                                        <li> <span class=\'fa fa-hdd-o\'></span><strong>Traffic cap </strong> 60G</li>");
document.writeln("										<li><span class=\'highlight-red\'>Ordinary VIP line</span></li>");
document.writeln("                                        <li> <span class=\'fa fa-bell\'></span><strong>System Support </strong> Win / Mac / Android / iPhone iPad / PS / Xbox</li>");
document.writeln("                                        <li> <span class=\'fa fa-upload\'></span><strong>For people：</strong> Query overseas study materials</li>");
document.writeln("                                        <li><span class=\'red\'>3Day unconditional refund</span> Seamlessly upgrade at any time</li>");
document.writeln("										<li> <span <strong>Monthly payment</strong> 10USD<br></li>");
document.writeln("										<li> <span <strong>Season pay</strong> 30USD<br></li>");
document.writeln("										<li> <span <strong>Six months</strong> 60USD<br></li>");
document.writeln("										<li> <span <strong>annual fee</strong> 120USD<br></li>");
document.writeln("										");
document.writeln("                                    </ul>");
document.writeln("                                    <div class=\'dt-sc-buy-now\'>");
document.writeln("                                        <a class=\'dt-sc-button small\' href=\'/cart.php?a=add&pid=2\'> order now <span class=\'fa fa-arrow-right\'></span> </a>");
document.writeln("                                    </div> <!-- **dt-sc-buy-now - Ends** -->");
document.writeln("                                    ");
document.writeln("                                </div> <!-- **dt-sc-pr-tb-col - Ends** -->");
document.writeln("                                </div> ");
document.writeln("                                ");
document.writeln("                                <div class=\'column dt-sc-one-fourth\'>");
document.writeln("                                    <!-- **dt-sc-pr-tb-col - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-pr-tb-col type3\'>");
document.writeln("                                    <!-- **dt-sc-tb-header - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-tb-header\'>");
document.writeln("                                        <!-- **dt-sc-price - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-price\'>");
document.writeln("                                            <div class=\'dt-sc-price-content\'>");
document.writeln("                                            	<h2> $20.00USD </h2>");
document.writeln("                                            	<span>/ month</span>");
document.writeln("                                            </div>");
document.writeln("                                        </div> <!-- **dt-sc-price - Ends** -->");
document.writeln("                                        <!-- **dt-sc-tb-title - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-tb-title\'>");
document.writeln("                                            <h5> Standard VIP </h5>");
document.writeln("                                        </div> <!-- **dt-sc-tb-title - Ends** -->");
document.writeln("                                    </div><!-- **dt-sc-tb-header - Ends** -->");
document.writeln("                                    <ul class=\'dt-sc-tb-content\'>");
document.writeln("                                        <li> <span class=\'fa fa-hdd-o\'></span><strong>Traffic cap </strong> 120G</li>");
document.writeln("										<li><span class=\'highlight-red\'>Standard VIP line</span></li>");
document.writeln("                                        <li> <span class=\'fa fa-bell\'></span><strong>System Support </strong> Win / Mac / Android / iPhone iPad / PS / Xbox</li>");
document.writeln("                                        <li> <span class=\'fa fa-upload\'></span><strong>For people：</strong> Search overseas information, foreign company staff</li>");
document.writeln("                                        <li><span class=\'red\'>3Day unconditional refund</span> Seamlessly upgrade at any time</li>");
document.writeln("										<li> <span <strong>Monthly payment</strong> 20USD<br></li>");
document.writeln("										<li> <span <strong>Season pay</strong> 60USD<br></li>");
document.writeln("										<li> <span <strong>Six months</strong> 120USD<br></li>");
document.writeln("										<li> <span <strong>annual fee</strong> 240USD<br></li>");
document.writeln("										");
document.writeln("                                    </ul>");
document.writeln("                                    <div class=\'dt-sc-buy-now\'>");
document.writeln("                                        <a class=\'dt-sc-button small\' href=\'/cart.php?a=add&pid=3\'> order now <span class=\'fa fa-arrow-right\'></span> </a>");
document.writeln("                                    </div> <!-- **dt-sc-buy-now - Ends** -->");
document.writeln("                                    ");
document.writeln("                                </div> <!-- **dt-sc-pr-tb-col - Ends** -->");
document.writeln("                                </div> ");
document.writeln("                                ");
document.writeln("                                <div class=\'column dt-sc-one-fourth\'>");
document.writeln("                                    <!-- **dt-sc-pr-tb-col - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-pr-tb-col type3\'>");
document.writeln("                                    <!-- **dt-sc-tb-header - Starts** -->");
document.writeln("                                    <div class=\'dt-sc-tb-header\'>");
document.writeln("                                        <!-- **dt-sc-price - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-price\'>");
document.writeln("                                            <div class=\'dt-sc-price-content\'>");
document.writeln("                                            	<h2> $40.00USD </h2>");
document.writeln("                                            	<span>/ month</span>");
document.writeln("                                            </div>");
document.writeln("                                        </div> <!-- **dt-sc-price - Ends** -->");
document.writeln("                                        <!-- **dt-sc-tb-title - Starts** -->");
document.writeln("                                        <div class=\'dt-sc-tb-title\'>");
document.writeln("                                            <h5> Advanced VIP </h5>");
document.writeln("                                        </div> <!-- **dt-sc-tb-title - Ends** -->");
document.writeln("                                    </div><!-- **dt-sc-tb-header - Ends** -->");
document.writeln("                                    <ul class=\'dt-sc-tb-content\'>");
document.writeln("                                        <li> <span class=\'fa fa-hdd-o\'></span><strong>Traffic cap </strong> Unlimited traffic</li>");
document.writeln("										<li><span class=\'highlight-red\'>Advanced VIP lines</span></li>");
document.writeln("                                        <li> <span class=\'fa fa-bell\'></span><strong>System Support </strong> Win / Mac / Android / iPhone iPad / PS / Xbox</li>");
document.writeln("                                        <li> <span class=\'fa fa-upload\'></span><strong>For people：</strong> Acceleration of overseas games, foreign trade</li>");
document.writeln("                                        <li><span class=\'red\'>3Day unconditional refund</span> Seamlessly upgrade at any time</li>");
document.writeln("										<li> <span <strong>Monthly payment</strong> 40USD<br></li>");
document.writeln("										<li> <span <strong>Season pay</strong> 120USD<br></li>");
document.writeln("										<li> <span <strong>Six months</strong> 240USD<br></li>");
document.writeln("										<li> <span <strong>annual fee</strong> 480USD<br></li>");
document.writeln("										");
document.writeln("                                    </ul>");
document.writeln("                                    <div class=\'dt-sc-buy-now\'>");
document.writeln("                                        <a class=\'dt-sc-button small\' href=\'/cart.php?a=add&pid=4\'> order now <span class=\'fa fa-arrow-right\'></span> </a>");
document.writeln("                                    </div> <!-- **dt-sc-buy-now - Ends** -->");
document.writeln("                                    ");
document.writeln("                                </div> <!-- **dt-sc-pr-tb-col - Ends** -->");
document.writeln("                                </div> ");
document.writeln("                        ");
document.writeln("                        </div> <!-- **dt-sc-pricing-table - Ends** -->");
document.writeln("                        ");
document.writeln("                    </div>");
document.writeln("");
document.writeln("	</div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	</div></div></section>");
document.writeln("	");
document.writeln("	");
document.writeln("	    <div id=\'responsive\' class=\'bg-dark\'>");
document.writeln("      <div class=\'text-center\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("          <div class=\'m-t-xl m-b-xl wrapper\'>");
document.writeln("            <h3 class=\'text-white\'>Stable running on mainstream operating systems such as Windows / iOS / Android / Mac OS</h3>");
document.writeln("            <p>By the majority of IT programmers, academic researchers, video enthusiasts, foreign trade companies need to visit overseas people\'s favorite.</p>");
document.writeln("          </div>");
document.writeln("          <div class=\'row m-t-xl m-b-xl\'>");
document.writeln("		    <div class=\'col-sm-3 wrapper-xl\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("              <p class=\'text-center h2 m-b-lg m-t-lg\'>");
document.writeln("                <span class=\'fa-stack fa-2x\'>");
document.writeln("				<a href=\'/clientarea.php\'>");
document.writeln("                  <i class=\'fa fa-circle fa-stack-2x text-dark\'></i>");
document.writeln("                  <i class=\'fa fa-apple fa-stack-1x text-muted\'></i>");
document.writeln("                </a></span><a href=\'/clientarea.php\'>");
document.writeln("              </a></p><a href=\'/clientarea.php\'>");
document.writeln("              <span class=\'text-primary text-ul\'>iOS</span></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 wrapper-xl\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("              <p class=\'text-center h2 m-b-lg m-t-lg\'>");
document.writeln("                <span class=\'fa-stack fa-2x\'>");
document.writeln("				<a href=\'/clientarea.php\'>");
document.writeln("                  <i class=\'fa fa-circle fa-stack-2x text-dark\'></i>");
document.writeln("                  <i class=\'fa fa-android fa-stack-1x text-muted\'></i>");
document.writeln("                </a></span><a href=\'/clientarea.php\'>");
document.writeln("              </a></p><a href=\'/clientarea.php\'>");
document.writeln("              <span class=\'text-primary text-ul\'>Android</span></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 wrapper-xl\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("              <p class=\'text-center h2 m-b-lg m-t-lg\'>");
document.writeln("                <span class=\'fa-stack fa-2x\'>");
document.writeln("				<a href=\'/clientarea.php\'>");
document.writeln("                  <i class=\'fa fa-circle fa-stack-2x text-dark\'></i>");
document.writeln("                  <i class=\'fa fa-windows fa-stack-1x text-muted\'></i>");
document.writeln("                </a></span><a href=\'/clientarea.php\'>");
document.writeln("              </a></p><a href=\'/clientarea.php\'>");
document.writeln("              <span class=\'text-primary text-ul\'>Windows</span></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 wrapper-xl\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("              <p class=\'text-center h2 m-b-lg m-t-lg\'>");
document.writeln("                <span class=\'fa-stack fa-2x\'>");
document.writeln("				<a href=\'/clientarea.php\'>");
document.writeln("                  <i class=\'fa fa-circle fa-stack-2x text-dark\'></i>");
document.writeln("                  <i class=\'fa fa-laptop fa-stack-1x text-muted text-md\'></i>");
document.writeln("                </a></span><a href=\'/clientarea.php\'>");
document.writeln("              </a></p><a href=\'/clientarea.php\'>");
document.writeln("              <span class=\'text-primary text-ul\'>Mac</span></a>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div> ");
document.writeln("</section>");
document.writeln("<footer id=\'footer\'>");
document.writeln("  	<div class=\'bg-primary text-center\'>");
document.writeln("      <div class=\'container wrapper\'>");
document.writeln("        <div class=\'m-t-xl m-b\'>");
document.writeln("          Click below to start your stable high speed internet experience.");
document.writeln("          <a href=\'clientarea.php\' class=\'btn btn-lg btn-dark b-white bg-empty m-sm\'>Landing use</a>");
document.writeln("          <a href=\'register.php\' class=\'btn btn-lg btn-warning b-white bg-empty m-sm\'>register account</a>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <i class=\'fa fa-caret-down fa-4x text-primary m-b-n-lg block\'></i>");
document.writeln("	</div>");
document.writeln("  ");
document.writeln("	<div class=\'bg-dark dker wrapper\'>");
document.writeln("		<div class=\'container text-center m-t-lg\'>");
document.writeln("			<div class=\'row m-t-xl m-b-xl\'>");
document.writeln("				<div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInLeft\' data-delay=\'300\'>");
document.writeln("					<i class=\'fa fa-bullhorn fa-3x icon-muted\'></i>");
document.writeln("					<h5 class=\'text-uc m-b m-t-lg\'>Disclaimer</h5>");
document.writeln("					<p class=\'text-sm\'>use <a href=\'index.php\' title=\'云鸟\'>[Cloud Bird Network Acceleration]</a> Please comply with local laws <br>");
document.writeln("						Cloudbird Network Acceleration does not assume any responsibility for the use of this service.");
document.writeln("             ");
document.writeln("             	</p>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInUp\' data-delay=\'600\'>");
document.writeln("					<i class=\'fa fa-ticket fa-3x icon-muted\'></i>");
document.writeln("					<h5 class=\'text-uc m-b m-t-lg\'>Work Order Service</h5>");
document.writeln("					<p class=\'text-sm\'><a href=\'clientarea.php\'>Online Work Order Technical Support, Fastest Reply</a><br> Any questions during the use of this site are welcome to submit work orders.</p>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-sm-4\' data-ride=\'animated\' data-animation=\'fadeInRight\' data-delay=\'900\'>");
document.writeln("					<i class=\'fa fa-desktop fa-3x icon-muted\'></i>");
document.writeln("					<h5 class=\'text-uc m-b m-t-lg\'>Remote support</h5>");
document.writeln("					<p class=\'text-sm\'></p><div class=\'follow-us\'>Telegram：<a href=\'https://t.me/cloudinbird\'>cloudinbird</a><br></p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<br>");
document.writeln("			<div class=\'m-t-xl m-b-xl\'>");
document.writeln("				<p> ");
document.writeln("            <a href=\'index.php#content\' data-jump=\'true\' class=\'btn btn-icon btn-rounded btn-dark b-dark bg-empty m-sm text-muted\'><i class=\'fa fa-angle-up\'></i></a>");
document.writeln("          	</p>");
document.writeln("			</div>");
document.writeln("			<div class=\'m-t-xl m-b-xl\'>");
document.writeln("				<p> ");
document.writeln("            Powered By<a href=\'/index.php\' class=\'b-dark bg-empty m-sm text-muted\'>Cloudbird Network Acceleration</a>");
document.writeln("          	</p>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</footer>");
document.writeln("");
document.writeln("   <script src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/js/jquery.min.js\'></script>");
document.writeln("  <script src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/js/bootstrap.js\'></script>");
document.writeln("  <script src=\'https://cdn.jsdelivr.net/gh/myklss/cdnjs@master/cloudinbird/theme/freedom/js/app.js\'></script>");
document.writeln("  </body>");